-- title:  Rust Land Generator
-- author: AlexanDDOS
-- desc:   A tech demo of destructible land/terrain generator for TIC-80 written in Rust and compiled into WASM. Full description: https://github.com/AlexanDDOS/tic80-land-generator
-- script: wasm